// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyignowdrwcnepjrxzyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5aWdub3dkcndjbmVwanJ4enl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTI3NzYsImV4cCI6MjA2Nzk4ODc3Nn0.txjy4lhJG86lz3q8CFnJJaFkPdQsGAZ7M2849GBjg2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});